version: 2

jobs:
    build:
        docker:
            -   image: cimg/php:8.3
        steps:
            - checkout
            -   run: sudo apt update
            -   restore_cache:
                    keys:
                        - v1-dependencies-{{ checksum "composer.lock" }}
                        - v1-dependencies-
            -   run: composer install -n --prefer-dist
            -   save_cache:
                    key: v1-dependencies-{{ checksum "composer.lock" }}
                    paths:
                        - ./vendor
            -   run: ./vendor/bin/phpunit
            -   run: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover coverage/clover/clover.xml --coverage-html coverage/html
            -   run: curl -Os https://uploader.codecov.io/latest/linux/codecov
            -   run: sudo chmod +x codecov
            -   run: ./codecov
